---
- name: this playbook install httpd
  hosts: all
  become: true
  tasks:
  - name: install package
    apt:
      name: apache2
      state: present
  - name: start service
    service:
      name: apache2
      state: started
